FROM rocker/r-ver:4.0.0

RUN apt-get update && apt-get install -y --no-install-recommends \
  libgit2-dev \
  libxml2-dev \
  libssl-dev \
  libz-dev \
  libcurl4-gnutls-dev \
  libsodium-dev

RUN mkdir /data

RUN mkdir /data/in
RUN mkdir /data/out


COPY run.R run.R

RUN R -e "install.packages('renv', repos = c(CRAN = 'https://cran.wu.ac.at/'))"


# at docker starts
CMD R -e "source('run.R')"

